{
 "title": "Climbing Stats",
 "description": "Statistics for Rock Climbing",
 "time": { "from": "2019-05-27T16:12:30.597Z", "to": "2019-09-07T10:13:37.216Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n<h1><span>Roped Climbing</span></h1>\n</div>\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Climbs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n date AS \"time\",\n count(id)\nFROM climbing\nWHERE\n $__timeFilter(date) AND\n type = 'toprope'\nORDER BY date"
    }
   ]
  },
  {
   "title": "Average Grade",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n date AS \"time\",\n grades.score\nFROM climbing\nINNER JOIN\n grades on climbing.grade=grades.grade\nWHERE\n $__timeFilter(date) and\n type = 'toprope'\nORDER BY date"
    }
   ]
  },
  {
   "title": "Total Climbs Per Grade",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n date AS \"time\",\n grade AS metric,\n count(grade) AS \"count(grade)\"\nFROM climbing\nWHERE\n $__timeFilter(date) AND\n type = 'toprope'\nGROUP BY grade,2\nORDER BY date"
    }
   ]
  },
  {
   "title": "Climbs over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n $__timeGroupAlias(date, 12h),\n grade AS metric,\n count(grade)\nFROM climbing\nWHERE\n $__timeFilter(date) AND\n type = 'toprope' OR\n type = 'sport'\nGROUP BY 1,2\nORDER BY $__timeGroup(date, 12h, 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "content": "<h1><center>Bouldering</h1>\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Climbs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n date AS \"time\",\n count(id)\nFROM climbing\nWHERE\n $__timeFilter(date) AND\n type = 'boulder'\nORDER BY date"
    }
   ]
  },
  {
   "title": "Total Climbs Per Grade",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n date AS \"time\",\n id\nFROM climbing\nWHERE\n $__timeFilter(date)\nORDER BY date"
    }
   ]
  },
  {
   "title": "Climbs over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n $__timeGroupAlias(date,24h,0),\n grade AS metric,\n count(grade)\nFROM climbing\nWHERE\n $__timeFilter(date) AND\n type = 'boulder'\nGROUP BY 1,2\nORDER BY $__timeGroup(date,24h,0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "content": "<h1><center>Misc</h1>\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Tape Color",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n date AS \"time\",\n color AS metric,\n count(color) AS \"count(color)\"\nFROM climbing\nWHERE\n $__timeFilter(date)\nGROUP BY color,2\nORDER BY date"
    }
   ]
  },
  {
   "title": "Total Climbs by Setter",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n date AS \"time\",\n setter AS metric,\n count(setter) AS \"count(setter)\"\nFROM climbing\nWHERE\n $__timeFilter(date)\nGROUP BY setter,2\nORDER BY date"
    }
   ]
  }
 ]
}